name: coveralls

on:
  push:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Enable Corepack
        run: corepack enable

      - name: Install
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Test
        run: pnpm run test -- --coverage

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
